package Vista;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class LoginForm extends JFrame {
    private JPanel mainPanel;
    private JTextField usuarioTextField;
    private JPasswordField passwordField;
    private JButton loginButton;
    private JComboBox<String> tipoUsuarioCombo;
    private JLabel tituloLabel;
    private JLabel usuarioLabel;
    private JLabel passwordLabel;
    private JLabel tipoLabel;

    public LoginForm() {
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setTitle("FarmaciaSoft - Login");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 350);
        setLocationRelativeTo(null);
        setResizable(false);

        loginButton.addActionListener(this::loginButtonActionPerformed);
        passwordField.addActionListener(e -> loginButton.doClick());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);

        tituloLabel = new JLabel();
        tituloLabel.setFont(new Font("Arial", Font.BOLD, 24));
        tituloLabel.setText("FarmaciaSoft");
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        mainPanel.add(tituloLabel, gbc);

        tipoLabel = new JLabel();
        tipoLabel.setText("Tipo de Usuario:");
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(tipoLabel, gbc);

        tipoUsuarioCombo = new JComboBox<>();
        tipoUsuarioCombo.setModel(new DefaultComboBoxModel<>(new String[]{"Administrador", "Empleado"}));
        gbc.gridx = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        mainPanel.add(tipoUsuarioCombo, gbc);

        usuarioLabel = new JLabel();
        usuarioLabel.setText("Usuario:");
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.NONE;
        gbc.weightx = 0;
        mainPanel.add(usuarioLabel, gbc);

        usuarioTextField = new JTextField();
        usuarioTextField.setColumns(15);
        gbc.gridx = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        mainPanel.add(usuarioTextField, gbc);

        passwordLabel = new JLabel();
        passwordLabel.setText("Contraseña:");
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.NONE;
        gbc.weightx = 0;
        mainPanel.add(passwordLabel, gbc);

        passwordField = new JPasswordField();
        passwordField.setColumns(15);
        gbc.gridx = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        mainPanel.add(passwordField, gbc);

        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weighty = 1.0;
        mainPanel.add(new JPanel(), gbc);

        loginButton = new JButton();
        loginButton.setFont(new Font("Arial", Font.BOLD, 14));
        loginButton.setText("Iniciar Sesión");
        loginButton.setPreferredSize(new Dimension(150, 35));
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.fill = GridBagConstraints.NONE;
        gbc.weighty = 0;
        mainPanel.add(loginButton, gbc);
    }

    private void loginButtonActionPerformed(ActionEvent e) {
        String usuario = usuarioTextField.getText().trim();
        String password = new String(passwordField.getPassword());
        String tipoUsuario = (String) tipoUsuarioCombo.getSelectedItem();

        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, complete todos los campos",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (tipoUsuario.equals("Administrador")) {
            Administrador adminPanel = new Administrador();
            adminPanel.setVisible(true);
            dispose();
        } else if (tipoUsuario.equals("Empleado")) {
            EmpleadoPanel empleadoPanel = new EmpleadoPanel();
            empleadoPanel.setVisible(true);
            dispose();
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            LoginForm login = new LoginForm();
            login.setVisible(true);
        });
    }
}
