package Vista;

import Controlador.EmpleadoController;
import Datos.*;
import Dominio.Cliente;
import Servicio.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class RegistroClienteForm extends JFrame {
    private JPanel mainPanel;
    private JTextField nombreTextField;
    private JTextField dniTextField;
    private JTextField telefonoTextField;
    private JButton registrarButton;
    private JButton cancelarButton;
    private EmpleadoController controller;

    public RegistroClienteForm() {
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setTitle("Registrar Cliente");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(450, 300);
        setLocationRelativeTo(null);

        inicializarController();
        configurarEventos();
    }

    private void inicializarController() {
        EmpleadoService empleadoService = new EmpleadoService(
                new UsuarioService(new ClienteDAO()),
                new DetalleVentaService(new DetalleVentaDAO()),
                new MedicamentoService(new MedicamentoDAO()),
                new VentaService(new VentaDAO()),
                new TicketService(new TicketDAO())
        );
        controller = new EmpleadoController(empleadoService);
    }

    private void configurarEventos() {
        registrarButton.addActionListener(this::registrarButtonActionPerformed);
        cancelarButton.addActionListener(e -> dispose());
    }

    private void registrarButtonActionPerformed(ActionEvent e) {
        String nombre = nombreTextField.getText().trim();
        String dni = dniTextField.getText().trim();
        String telefono = telefonoTextField.getText().trim();

        // Validación de campos
        if (nombre.isEmpty() || dni.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, complete todos los campos",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el cliente
        Cliente cliente = new Cliente(nombre, dni, telefono);

        // Registrar el cliente
        boolean exito = controller.agregarCliente(cliente);

        if (exito) {
            JOptionPane.showMessageDialog(this,
                    "Cliente registrado exitosamente",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Error al registrar el cliente. Verifique los datos e intente nuevamente.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        nombreTextField.setText("");
        dniTextField.setText("");
        telefonoTextField.setText("");
        nombreTextField.requestFocus();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial", Font.BOLD, 18, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Registrar Nuevo Cliente");
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        mainPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Nombre:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(label2, gbc);
        nombreTextField = new JTextField();
        nombreTextField.setColumns(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        mainPanel.add(nombreTextField, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("DNI:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(label3, gbc);
        dniTextField = new JTextField();
        dniTextField.setColumns(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        mainPanel.add(dniTextField, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Teléfono:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(label4, gbc);
        telefonoTextField = new JTextField();
        telefonoTextField.setColumns(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        mainPanel.add(telefonoTextField, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weighty = 1.0;
        mainPanel.add(spacer1, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        mainPanel.add(panel1, gbc);
        registrarButton = new JButton();
        registrarButton.setPreferredSize(new Dimension(120, 35));
        registrarButton.setText("Registrar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 5, 0, 5);
        panel1.add(registrarButton, gbc);
        cancelarButton = new JButton();
        cancelarButton.setPreferredSize(new Dimension(120, 35));
        cancelarButton.setText("Cancelar");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 5, 0, 5);
        panel1.add(cancelarButton, gbc);
    }

    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(java.util.Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new javax.swing.plaf.FontUIResource(font);
        return fontWithFallback;
    }

    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}



